from django.urls import re_path

from . import views


urlpatterns = [
    re_path(r"^$", views.home_view, name="home"),
    re_path(r"^about/$", views.about_view, name="about"),
    re_path(r"^about/update/$", views.company_info_update_view, name="company_info_update"),
    re_path(r"^about/delete/$", views.company_info_delete_view, name="company_info_delete"),
    re_path(r"^privacy/$", views.privacy_view, name="privacy"),
    re_path(r"^register/$", views.register_view, name="register"),
    re_path(r"^login/$", views.login_view, name="login"),
    re_path(r"^logout/$", views.logout_view, name="logout"),
    re_path(r"^set-timezone/$", views.set_timezone_view, name="set_timezone"),
    re_path(r"^articles/$", views.ArticleListView.as_view(), name="article_list"),
    re_path(r"^articles/create/$", views.ArticleCreateView.as_view(), name="article_create"),
    re_path(r"^articles/(?P<pk>\d+)/$", views.ArticleDetailView.as_view(), name="article_detail"),
    re_path(r"^articles/(?P<pk>\d+)/update/$", views.ArticleUpdateView.as_view(), name="article_update"),
    re_path(r"^articles/(?P<pk>\d+)/delete/$", views.ArticleDeleteView.as_view(), name="article_delete"),
    re_path(r"^reviews/$", views.review_list_view, name="review_list"),
    re_path(r"^reviews/(?P<pk>\d+)/delete/$", views.review_delete_view, name="review_delete"),
    re_path(r"^employees/$", views.EmployeeListView.as_view(), name="employee_list"),
    re_path(r"^employees/create/$", views.EmployeeCreateView.as_view(), name="employee_create"),
    re_path(r"^employees/(?P<pk>\d+)/update/$", views.EmployeeUpdateView.as_view(), name="employee_update"),
    re_path(r"^employees/(?P<pk>\d+)/delete/$", views.EmployeeDeleteView.as_view(), name="employee_delete"),
    re_path(r"^vacancies/$", views.VacancyListView.as_view(), name="vacancy_list"),
    re_path(r"^vacancies/create/$", views.VacancyCreateView.as_view(), name="vacancy_create"),
    re_path(r"^vacancies/(?P<pk>\d+)/update/$", views.VacancyUpdateView.as_view(), name="vacancy_update"),
    re_path(r"^vacancies/(?P<pk>\d+)/delete/$", views.VacancyDeleteView.as_view(), name="vacancy_delete"),
    re_path(r"^glossary/$", views.GlossaryListView.as_view(), name="glossary_list"),
    re_path(r"^glossary/create/$", views.GlossaryCreateView.as_view(), name="glossary_create"),
    re_path(r"^glossary/(?P<pk>\d+)/update/$", views.GlossaryUpdateView.as_view(), name="glossary_update"),
    re_path(r"^glossary/(?P<pk>\d+)/delete/$", views.GlossaryDeleteView.as_view(), name="glossary_delete"),
    re_path(r"^promocodes/$", views.promo_code_list_view, name="promocode_list"),
    re_path(r"^promocodes/create/$", views.PromoCodeCreateView.as_view(), name="promocode_create"),
    re_path(r"^promocodes/(?P<pk>\d+)/update/$", views.PromoCodeUpdateView.as_view(), name="promocode_update"),
    re_path(r"^promocodes/(?P<pk>\d+)/delete/$", views.PromoCodeDeleteView.as_view(), name="promocode_delete"),
    re_path(r"^rooms/$", views.RoomListView.as_view(), name="room_list"),
    re_path(r"^catalog/$", views.RoomCatalogListView.as_view(), name="room_catalog"),
    re_path(r"^catalog/(?P<pk>\d+)/$", views.RoomCatalogDetailView.as_view(), name="room_catalog_detail"),
    re_path(r"^rooms/create/$", views.RoomCreateView.as_view(), name="room_create"),
    re_path(r"^rooms/(?P<pk>\d+)/$", views.RoomDetailView.as_view(), name="room_detail"),
    re_path(r"^rooms/(?P<pk>\d+)/update/$", views.RoomUpdateView.as_view(), name="room_update"),
    re_path(r"^rooms/(?P<pk>\d+)/delete/$", views.RoomDeleteView.as_view(), name="room_delete"),
    re_path(r"^bookings/create/$", views.booking_create_view, name="booking_create"),
    re_path(r"^bookings/my/$", views.booking_user_view, name="booking_user"),
    re_path(r"^bookings/my/(?P<pk>\d+)/cancel/$", views.booking_cancel_view, name="booking_cancel"),
    re_path(r"^bookings/$", views.BookingListView.as_view(), name="booking_list"),
    re_path(r"^bookings/(?P<pk>\d+)/update/$", views.BookingUpdateView.as_view(), name="booking_update"),
    re_path(r"^bookings/(?P<pk>\d+)/delete/$", views.BookingDeleteView.as_view(), name="booking_delete"),
    re_path(r"^room-categories/$", views.RoomCategoryListView.as_view(), name="room_category_list"),
    re_path(r"^room-categories/create/$", views.RoomCategoryCreateView.as_view(), name="room_category_create"),
    re_path(
        r"^room-categories/(?P<pk>\d+)/update/$",
        views.RoomCategoryUpdateView.as_view(),
        name="room_category_update",
    ),
    re_path(
        r"^room-categories/(?P<pk>\d+)/delete/$",
        views.RoomCategoryDeleteView.as_view(),
        name="room_category_delete",
    ),
    re_path(r"^clients/$", views.ClientListView.as_view(), name="client_list"),
    re_path(r"^clients/create/$", views.ClientCreateView.as_view(), name="client_create"),
    re_path(r"^clients/(?P<pk>\d+)/update/$", views.ClientUpdateView.as_view(), name="client_update"),
    re_path(r"^clients/(?P<pk>\d+)/delete/$", views.ClientDeleteView.as_view(), name="client_delete"),
    re_path(r"^payments/$", views.PaymentListView.as_view(), name="payment_list"),
    re_path(r"^payments/create/$", views.PaymentCreateView.as_view(), name="payment_create"),
    re_path(r"^payments/(?P<pk>\d+)/update/$", views.PaymentUpdateView.as_view(), name="payment_update"),
    re_path(r"^payments/(?P<pk>\d+)/delete/$", views.PaymentDeleteView.as_view(), name="payment_delete"),
    re_path(r"^extra-services/$", views.ExtraServiceListView.as_view(), name="extra_service_list"),
    re_path(r"^extra-services/create/$", views.ExtraServiceCreateView.as_view(), name="extra_service_create"),
    re_path(r"^extra-services/(?P<pk>\d+)/update/$", views.ExtraServiceUpdateView.as_view(), name="extra_service_update"),
    re_path(r"^extra-services/(?P<pk>\d+)/delete/$", views.ExtraServiceDeleteView.as_view(), name="extra_service_delete"),
    re_path(r"^cabinet/$", views.client_cabinet_view, name="client_cabinet"),
    re_path(r"^cart/$", views.cart_view, name="cart_view"),
    re_path(r"^cart/add/(?P<pk>\d+)/$", views.cart_add_view, name="cart_add"),
    re_path(r"^cart/remove/(?P<pk>\d+)/$", views.cart_remove_view, name="cart_remove"),
    re_path(r"^cart/increase/(?P<pk>\d+)/$", views.cart_increase_view, name="cart_increase"),
    re_path(r"^cart/decrease/(?P<pk>\d+)/$", views.cart_decrease_view, name="cart_decrease"),
    re_path(r"^cart/payment/$", views.cart_payment_view, name="cart_payment"),
    re_path(r"^api/weather/$", views.weather_api_proxy, name="weather_api_proxy"),
    re_path(r"^api/currency/$", views.CurrencyApiProxyView.as_view(), name="currency_api_proxy"),
    re_path(r"^analytics/$", views.hotel_analytics_view, name="hotel_analytics"),
]
