# Generated by Django 5.2.14 on 2026-05-28 10:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import hotel.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('free', 'Свободен'), ('occupied', 'Занят'), ('cleaning', 'На уборке')], default='free', max_length=20)),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('short_content', models.CharField(max_length=255, validators=[hotel.models.validate_single_sentence])),
                ('full_text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='charts/')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'constraints': [models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='article_title_not_empty'), models.CheckConstraint(condition=models.Q(('short_content', ''), _negated=True), name='article_short_content_not_empty'), models.CheckConstraint(condition=models.Q(('full_text', ''), _negated=True), name='article_full_text_not_empty')],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(default='Новый клиент', max_length=255)),
                ('phone', models.CharField(default='+375 (29) 000-00-00', max_length=20)),
                ('birth_date', models.DateField(default=hotel.models.default_adult_birth_date)),
                ('has_children', models.BooleanField(default=False)),
                ('timezone', models.CharField(default='Europe/Minsk', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_text', models.TextField()),
                ('history_by_years', models.TextField()),
                ('company_details', models.TextField()),
            ],
            options={
                'verbose_name': 'О компании',
                'verbose_name_plural': 'О компании',
                'constraints': [models.CheckConstraint(condition=models.Q(('company_text', ''), _negated=True), name='company_info_text_not_empty'), models.CheckConstraint(condition=models.Q(('history_by_years', ''), _negated=True), name='company_info_history_not_empty'), models.CheckConstraint(condition=models.Q(('company_details', ''), _negated=True), name='company_info_details_not_empty')],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('work_description', models.TextField()),
                ('timezone', models.CharField(default='Europe/Minsk', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='ExtraService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'verbose_name': 'Дополнительная услуга',
                'verbose_name_plural': 'Дополнительные услуги',
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='extra_service_name_not_empty'), models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='extra_service_price_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('active', 'Активно'), ('canceled', 'Отменено'), ('finished', 'Завершено')], default='active', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='hotel.client')),
                ('extra_services', models.ManyToManyField(blank=True, related_name='bookings', to='hotel.extraservice')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='hotel.room')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': 'Термин / FAQ',
                'verbose_name_plural': 'Словарь терминов / FAQ',
                'constraints': [models.CheckConstraint(condition=models.Q(('question', ''), _negated=True), name='glossary_question_not_empty'), models.CheckConstraint(condition=models.Q(('answer', ''), _negated=True), name='glossary_answer_not_empty')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('paid', 'Оплачено'), ('pending', 'Ожидает')], default='pending', max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hotel.booking')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('active', 'Активен'), ('archived', 'В архиве')], default='active', max_length=20)),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'constraints': [models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='promo_code_not_empty'), models.CheckConstraint(condition=models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100)), name='promo_code_discount_valid_range')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(max_length=120)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField()),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'constraints': [models.CheckConstraint(condition=models.Q(('author_name', ''), _negated=True), name='review_author_name_not_empty'), models.CheckConstraint(condition=models.Q(('review_text', ''), _negated=True), name='review_text_not_empty'), models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_between_1_5')],
            },
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('capacity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'verbose_name': 'Категория номера',
                'verbose_name_plural': 'Категории номеров',
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='room_category_name_not_empty'), models.CheckConstraint(condition=models.Q(('description', ''), _negated=True), name='room_category_description_not_empty'), models.CheckConstraint(condition=models.Q(('base_price__gte', 0)), name='room_category_base_price_non_negative')],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='hotel.roomcategory'),
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('salary_level', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'constraints': [models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='vacancy_title_not_empty'), models.CheckConstraint(condition=models.Q(('description', ''), _negated=True), name='vacancy_description_not_empty'), models.CheckConstraint(condition=models.Q(('requirements', ''), _negated=True), name='vacancy_requirements_not_empty'), models.CheckConstraint(condition=models.Q(('salary_level', ''), _negated=True), name='vacancy_salary_level_not_empty')],
            },
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(condition=models.Q(('full_name', ''), _negated=True), name='client_full_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(condition=models.Q(('phone', ''), _negated=True), name='client_phone_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(condition=models.Q(('timezone', ''), _negated=True), name='client_timezone_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('full_name', ''), _negated=True), name='employee_full_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('position', ''), _negated=True), name='employee_position_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('phone', ''), _negated=True), name='employee_phone_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('work_description', ''), _negated=True), name='employee_work_description_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('timezone', ''), _negated=True), name='employee_timezone_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payment_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('total_cost__gte', 0)), name='booking_total_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('check_out_date__gt', models.F('check_in_date'))), name='booking_checkout_after_checkin'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(condition=models.Q(('room_number', ''), _negated=True), name='room_number_not_empty'),
        ),
    ]
