# Generated by Django 5.2.14 on 2026-06-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
    ]
