# Generated by Django 5.2.14 on 2026-06-03 17:23

import hotel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_article_created_at_alter_article_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(default=hotel.models.default_adult_birth_date),
        ),
    ]
