# Generated by Django 5.2.14 on 2026-06-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_employee_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='has_children',
        ),
        migrations.AddField(
            model_name='client',
            name='children_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
