# Generated by Django 5.2.14 on 2026-09-13 20:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_client_first_name_client_last_name_client_patronymic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image_url', models.URLField(verbose_name='Ссылка на изображение')),
                ('link_url', models.URLField(blank=True, verbose_name='Ссылка баннера')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Текст для alt')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Рекламный баннер',
                'verbose_name_plural': 'Рекламные баннеры',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('logo_url', models.URLField(verbose_name='Ссылка на логотип')),
                ('website_url', models.URLField(verbose_name='Сайт компании')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
